var data = [
	[
		{"title":"电流分有？","type":2,"optionList":[{"id":"A","content":"直流"},{"id":"B","content":"交流"},{"id":"C","content":"直流和交流"}],"answer":"C","userAnswer":"","userFavor":false,"explain":"科技学依据","score":20},
		{"title":"水是液体？","type":1,"optionList":[{"id":"A","content":"对"},{"id":"B","content":"错"}],"answer":"A","userAnswer":"","userFavor":false,"explain":"难到是固体不成？","score":20},
		{"title":"酸菜鱼的味道？","type":3,"optionList":[{"id":"A","content":"咸味"},{"id":"B","content":"辣味"},{"id":"C","content":"甜味"},{"id":"D","content":"酸味"}],"answer":"ABD","userAnswer":"","userFavor":false,"explain":"你怎么想都行，要的就是这个味，答案只能选A,B,D","score":20},				
		{"title":"床前（____）光，疑是地上霜。","type":4,"optionList":[{"id":"","content":""}],"answer":"明月","userAnswer":"","userFavor":false,"explain":"问答题没有选项，无法做答，且不参与计分","score":20},
		{"material":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-7题：","title":"水是液体？","type":5,"optionList":[{"id":"A","content":"对"},{"id":"B","content":"错"}],"answer":"A","userAnswer":"","userFavor":false,"explain":"难到是固体不成？","score":20},	
	],
	[
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"1"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"2"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"3"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"4"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"5"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"6"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"7"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"8"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"dd","uIsTrue":null,"QTypeID":"D","QText4":"主观性","uAnsText":" ","QText3":"普遍性","Score":"2.0","QText2":"客观性","QText1":"特殊性","AnsText":"C","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uScore":null,"QuestionOrder":"9"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"1"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"2"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"3"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"4"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"5"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"6"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"7"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"8"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"9"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"10"},
		{"AddNo":null,"uIsDone":null,"AnsParsing":"aa","uIsTrue":null,"QTypeID":"F","QText5":null,"QText4":"外出用餐时，尽量不使用一次性筷子","uAnsText":" ","QText3":"在自然光能够满足照明需要的情况下，关闭室内照明灯","Score":"3.0","QText2":"信奉\u201c师徒如父子\u201d的观念，一切按照师傅的要求做事","QText1":"根据实际，从业人员每日适当减少食物的摄入量","AnsText":"BCD  ","Question":"建设节约型社会，要求（）。","uScore":null,"QuestionOrder":"11"},
		{"AddNo":null,"uAnsText":null,"uIsDone":null,"Score":"10.0","AnsParsing":"xx","AnsText":"道德具有鲜明的阶级性、社会共同性和（）。","Question":"道德具有鲜明的阶级性、社会共同性和（）。","uIsTrue":null,"uScore":null,"QTypeID":"J","QuestionOrder":"1"},
		{"AddNo":null,"uAnsText":" ","uIsDone":null,"Score":"5.0","AnsParsing":"一般情况下,从业人员的着装要求是朴素大方。","AnsText":"T","Question":"一般情况下,从业人员的着装要求是注重品牌。","uIsTrue":null,"uScore":null,"QTypeID":"P","QuestionOrder":"1"},
		{"AddNo":null,"uAnsText":" ","uIsDone":null,"Score":"5.0","AnsParsing":"一般情况下,从业人员的着装要求是朴素大方。","AnsText":"T","Question":"一般情况下,从业人员的着装要求是注重品牌。","uIsTrue":null,"uScore":null,"QTypeID":"P","QuestionOrder":"2"},
		{"AddNo":null,"uAnsText":" ","uIsDone":null,"Score":"5.0","AnsParsing":"一般情况下,从业人员的着装要求是朴素大方。","AnsText":"T","Question":"一般情况下,从业人员的着装要求是注重品牌。","uIsTrue":null,"uScore":null,"QTypeID":"P","QuestionOrder":"3"},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"1","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"1","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"2","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"2","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"3","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"3","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"4","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"4","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"5","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"5","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"6","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"6","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"7","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"7","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"8","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"8","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"9","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"9","uSubScore":null},
		{"Addno":"510","uIsDone":null,"SubQuestion":"收受名片时，以下做法欠妥当的是（  ）。","AnsParsing":null,"SubScore":"2.0","Mid":"81","SubOrder":"10","uIsTrue":null,"QTypeID":"Z","TestID":"12","QText4":"既不可用手揉搓名片表面，\n也不可把对方名片当做记事簿","uAnsText":null,"Score":"8.0","QText3":"把名片放在抽屉里保管","QText2":"认真看过名片，轻轻念完其姓名、职位","QText1":"接待人员应恭敬地双手接受","AnsText":"C","Question":"日常事务接待是指对平时来机关单位办理各种具体业务、事务的各类人员的接待工作。\n这种接待时间短，务实性强，看似平常琐碎，但处理不好就有可能会影响单位的声誉和形象，这就要求有关人员必须了解和掌握日常接待的一般内容和环节。阅读以上材料，回答1-4题：","QuestionOrder":"10","uSubScore":null},
	
		
	],
	[
		{"uIsTrue":"0","QTypeID":"D","QuestionOrder":"1"}, 
		{"uIsTrue":null,"QTypeID":"D","QuestionOrder":"2"},
		{"uIsTrue":null,"QTypeID":"D","QuestionOrder":"3"}, 
		{"uIsTrue":"1","QTypeID":"D","QuestionOrder":"4"},
		{"uIsTrue":null,"QTypeID":"D","QuestionOrder":"5"},
		{"uIsTrue":null,"QTypeID":"D","QuestionOrder":"6"}, 
		{"uIsTrue":null,"QTypeID":"D","QuestionOrder":"7"}, 
		{"uIsTrue":null,"QTypeID":"D","QuestionOrder":"8"}, 
		{"uIsTrue":null,"QTypeID":"D","QuestionOrder":"9"},
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"1"},
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"2"}, 
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"3"}, 
		{"uIsTrue":"1","QTypeID":"F","QuestionOrder":"4"}, 
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"5"},
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"6"}, 
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"7"}, 
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"8"},
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"9"},
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"10"}, 
		{"uIsTrue":null,"QTypeID":"F","QuestionOrder":"11"}, 
		{"uIsTrue":null,"QTypeID":"J","QuestionOrder":"1"},
		{"uIsTrue":null,"QTypeID":"P","QuestionOrder":"1"}, 
		{"uIsTrue":null,"QTypeID":"P","QuestionOrder":"2"}, 
		{"uIsTrue":null,"QTypeID":"P","QuestionOrder":"3"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"1"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"2"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"3"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"4"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"5"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"6"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"7"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"8"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"9"}, 
		{"uIsTrue":null,"QTypeID":"Z","QuestionOrder":"10"}
		,
		
	]
];
export default data;